/**
* @file debug.hpp
 * @brief Utilities for visualizing and debugging the calculator's internal pipeline.
 * @details This header provides functions intended for development and verbose CLI modes.
 * It allows developers to inspect the token stream generated by the Lexer before it
 * is consumed by the Parser, ensuring grammatical and structural accuracy.
 */

#pragma once

#include <vector>
#include <string>

#include "cli/cli.hpp"
#include "lexer/def_token.hpp"
#include "parse/def_ast.hpp"


/**
 * @brief Converts a TokenType enum classification into a human-readable string.
 * @details Used primarily for formatting debug output and detailed error messages.
 * Instead of printing integer enum values, this translates the type back to
 * its string literal representation.
 * * @param type The TokenType enum value to evaluate.
 * @return A std::string representation of the enum (e.g., "OPERATOR", "NUMBER").
 */
std::string token_type_to_string(TokenType type);

/**
 * @brief Formats the token stream and prints it via the CLI module.
 * @param tokens The vector of Token objects generated by the Lexer.
 */
void print_token_stream(const std::vector<Token>& tokens);

/**
 * @brief Visually prints the Abstract Syntax Tree structure to the CLI.
 * @param root A pointer to the root node of the parsed AST.
 */
void print_ast(const ASTNode* root);

/**
 * @brief Visually prints the Abstract Syntax Tree structure to the CLIas a graphviz.
 * @param root A pointer to the root node of the parsed AST.
 */
void print_ast_graphviz(const ASTNode* root);